### ISSUE TITLE
Application crashes on startup

### ISSUE THREAD

**Issue by Mohaymin** [Teachmint/teachstack-sdk-test-application#1]
Whenever I run this app, I get the following exception:
```
2022-03-10 15:59:46.100 20241-20241/com.teachmint.testapplication E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.teachmint.testapplication, PID: 20241
    android.app.RemoteServiceException: Bad notification(tag=null, id=22222) posted from package com.teachmint.testapplication, crashing app(uid=10346, pid=20241): Couldn't create icon: StatusBarIcon(icon=Icon(typ=RESOURCE pkg=com.teachmint.testapplication id=0x000011d1) visible user=0 )
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1976)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7590)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by rahulsain-ingeniumedu** [comment]
any solution?
